# ========= ========
    #Build Environment
# ========= ========
FROM node:16.20.0-alpine3.18 AS build

ARG REACT_APP_BACKEND_URL

WORKDIR /three-doctors-frontend

ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

COPY package*.json .

RUN npm install

COPY . .

# create build artifacts from stage 0
RUN npm run build 

# ========= ========
    #Prod Environment
# ========= ========

FROM nginx:stable-alpine-slim

# copy the updated virtual server configuration to replace the default Nginx configuration
COPY --from=build /three-doctors-frontend/nginx.conf /etc/nginx/nginx.conf

# copy only the production-related application code from the image built by the previous stage
COPY --from=build /three-doctors-frontend/dist /usr/share/nginx/html

EXPOSE 5173